services:
  api:
    build: .
    container_name: dean_office_api
    ports:
      - "3010:3010"
    volumes:
      - .:/app_code
      - db_data:/app_code/data
    environment:
      - PYTHONUNBUFFERED=1
      - JWT_SECRET_KEY=my-dev-secret-key-32-chars-long!!
      # ПР7: Богдан — змінна оточення для ключа шифрування Fernet
      # Ключ використовується для шифрування персональних даних і backup-файлів
      - ENCRYPTION_KEY=MkpMr1R73rfS-cxZJ6uaqcRhZiWRJcbRu7HRd8UPx9s=

volumes:
  db_data:
# docker config
